-- 8차시: 대여·반납 기록을 DB에 저장하기 (Supabase > SQL Editor 에서 Run)
-- 여러 번 실행해도 안전하다.

-- 1) 대여 기록표 : 대여 1번 = 1줄
create table if not exists rentals (
  id           integer generated by default as identity primary key,
  inventory_id integer not null references inventory(id) on delete cascade,
  borrower     text not null default '',      -- 대여한 사람 (학번/이름, 비워도 됨)
  rented_at    timestamptz default now(),      -- 대여 시각 (옛 기록은 모를 수 있어 비어 있을 수 있음)
  returned_at  timestamptz                     -- 반납 시각 (아직 안 돌려줬으면 비어 있음)
);

-- 이미 "사용중"인 재고(예시 데이터의 3번, 8번)에도 대여 기록 한 줄씩 만들어 둔다
insert into rentals (inventory_id, borrower, rented_at)
select i.id, '', null
from inventory i
where i.status = '사용중'
  and not exists (select 1 from rentals r where r.inventory_id = i.id and r.returned_at is null);

-- 2) 보안 설정(RLS)
alter table rentals enable row level security;

drop policy if exists "rentals 읽기" on rentals;
create policy "rentals 읽기" on rentals for select using (true);

-- 대여 기록 추가: "아직 반납 안 된" 상태로만 만들 수 있다
drop policy if exists "rentals 추가" on rentals;
create policy "rentals 추가" on rentals for insert
  with check (returned_at is null and char_length(borrower) <= 20);

-- 반납: 열려 있는 기록에 반납 시각을 채우는 것만 가능
drop policy if exists "rentals 반납" on rentals;
create policy "rentals 반납" on rentals for update
  using (returned_at is null)
  with check (returned_at is not null);

-- 고칠 수 있는 칸을 제한한다: rentals 는 returned_at 만, inventory 는 status 만
revoke update on rentals from anon;
grant update (returned_at) on rentals to anon;

drop policy if exists "inventory 상태변경" on inventory;
create policy "inventory 상태변경" on inventory for update
  using (true)
  with check (status in ('보관중', '사용중'));

revoke update on inventory from anon;
grant update (status) on inventory to anon;
