-- 시약관리대장 DB 구조 (6차시)
-- Supabase > SQL Editor 에 통째로 붙여넣고 Run 하면 테이블이 만들어진다.
-- 여러 번 실행해도 안전하다. (이미 있으면 건너뜀)

-- 시약 정보 (MSDS에서 가져온 내용) : 시약 1종 = 1줄
create table if not exists reagents (
  name          text primary key,              -- 시약명 (예: 에탄올)
  categories    text[] not null default '{}',  -- 카테고리 태그 (예: {유기,산})
  official_name text,                          -- MSDS 정식 명칭
  cas           text,                          -- CAS 번호
  chem_id       text,                          -- KOSHA 물질 번호
  hazard        text,                          -- 위험성
  properties    text,                          -- 물리화학적 특성
  handling      text,                          -- 취급·저장방법
  first_aid     text                           -- 응급조치
);

-- 재고 : 시약병 1개 = 1줄
create table if not exists inventory (
  id           integer generated by default as identity primary key, -- 재고번호
  reagent_name text not null references reagents(name) on update cascade,
  purchased_on date,                           -- 구매일
  opened_on    date,                           -- 개봉일 (미개봉이면 비움)
  expires_on   date,                           -- 유효기한
  amount       text check (amount in ('상','중','하')),             -- 남은 양
  location     text,                           -- 보관 위치 (시약장 칸)
  status       text not null default '보관중' check (status in ('보관중','사용중')),
  note         text not null default ''
);

-- 보안 설정(RLS): 지금은 "읽기"만 허용한다.
-- 쓰기(재고 추가, 대여/반납)는 7·8차시에 필요한 만큼만 추가한다.
alter table reagents  enable row level security;
alter table inventory enable row level security;

drop policy if exists "reagents 읽기"  on reagents;
drop policy if exists "inventory 읽기" on inventory;
create policy "reagents 읽기"  on reagents  for select using (true);
create policy "inventory 읽기" on inventory for select using (true);
